"""Scenario families for the hazard categories: FIRE, FLOODING,
SEVERE_WEATHER, EARTHQUAKE.

Ladder severities are assigned across the four ladders in each category so
that every category contributes LOW, MEDIUM, HIGH and CRITICAL in roughly
equal measure. That is deliberate: it makes the category statistically
useless as a predictor of severity, forcing the evidence in the text to
carry that decision.
"""

from __future__ import annotations

from .schema import (
    F,
    KIND_AMBIGUOUS,
    KIND_CONFLICTING,
    KIND_FALSE_POSITIVE,
    KIND_INFO,
    KIND_MULTI_MESSAGE,
    L,
)

FIRE_FAMILIES = [
    F(
        "fire_smoke_to_confirmed_ladder",
        "FIRE",
        [
            L(
                "LOW", "OPEN",
                ["faint burning smell near the {asset} at {loc}, nothing visible, going to check",
                 "someone reports a burnt smell round the {asset} in {loc}, no smoke seen"],
                "A burning smell was reported near the {asset} at {loc} with nothing visible; a check is underway.",
                cause="unknown, smell only", asset="{asset}", resources=["site check"], hint="{loc}",
                note="Smell alone establishes almost nothing — severity stays low until something is seen.",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["visible smoke coming off the {asset} at {loc}, no flames yet, we've cleared the area",
                 "smoke now showing from the {asset}, {loc}, area pushed back, no one inside as far as we know"],
                "Visible smoke is coming from the {asset} at {loc}; the area has been cleared with no flames yet observed.",
                cause="fire, source not yet identified", asset="{asset}",
                resources=["fire response"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["confirmed fire at the {asset} {loc}, flames through the roof, {count} people still inside",
                 "{asset} at {loc} well alight, {count} unaccounted for inside, we cannot get in"],
                "A confirmed fire at the {asset} in {loc} has flames through the structure with {count} people still inside and no safe entry.",
                cause="confirmed structure fire", asset="{asset}",
                entities=["{count} people still inside"],
                resources=["fire brigade", "rescue team", "ambulance"], hint="{loc}",
            ),
        ],
        slots={"asset": ["store shed", "workshop", "generator hut", "supply building", "kitchen block"]},
    ),
    F(
        "fire_vehicle_roadside_ladder",
        "FIRE",
        [
            L(
                "MEDIUM", "RESTRICTED",
                ["a {vehicle} on the {loc} road is smoking from the engine, driver's out and clear",
                 "{vehicle} pulled over at {loc} with smoke from under the bonnet, occupants already out"],
                "A {vehicle} at {loc} is smoking from the engine; the occupants are out and clear.",
                cause="suspected vehicle fault", asset="{vehicle}",
                resources=["fire extinguisher", "traffic control"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["{vehicle} fully alight on the {loc} road, everyone out, but it's blocking the lane",
                 "vehicle fire at {loc}, {vehicle} burning, occupants safe, road not passable"],
                "A {vehicle} is fully alight at {loc}, blocking the road; all occupants are out safely.",
                cause="vehicle fire", asset="{vehicle}",
                resources=["fire response", "road closure"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["{vehicle} burning at {loc} next to the fuel store, fire spreading, {count} people evacuating the area",
                 "vehicle fire at {loc} has caught the fuel drums, {count} people moving out, this is going badly"],
                "A vehicle fire at {loc} has spread to a fuel store, forcing {count} people to evacuate the area.",
                cause="vehicle fire spread to fuel storage", asset="{vehicle}",
                entities=["{count} people evacuating"],
                resources=["fire brigade", "evacuation support"], hint="{loc}",
            ),
        ],
        slots={"vehicle": ["truck", "van", "pickup", "minibus", "tractor"]},
    ),
    F(
        "fire_waste_pile_ladder",
        "FIRE",
        [
            L(
                "LOW", "OPEN",
                ["small rubbish fire behind {loc}, contained to the pile, we're putting it out now",
                 "bit of a waste fire at the back of {loc}, small, being dealt with"],
                "A small contained rubbish fire behind {loc} is being extinguished on site.",
                cause="waste burning", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["waste fire at {loc} has spread to the fence line, still small but we need more than buckets",
                 "rubbish fire near {loc} getting into the boundary fence, beyond what we can handle here"],
                "A waste fire at {loc} has spread to the boundary fence and now exceeds on-site capacity.",
                cause="waste fire spread", resources=["fire response"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["the waste fire at {loc} is now up against the stores, wind pushing it towards the tents",
                 "fire at {loc} spreading toward the store tents, wind behind it, need help fast"],
                "A waste fire at {loc} is spreading under wind toward stores and tents.",
                cause="waste fire spreading under wind", resources=["fire brigade"], hint="{loc}",
            ),
        ],
    ),
    F(
        "fire_scorch_damage_ladder",
        "FIRE",
        [
            L(
                "LOW", "OPEN",
                ["found scorch marks on the wall by the {asset} at {loc}, cold, must have been a while ago",
                 "there's old burn marks near the {asset}, {loc}, nothing burning now, reporting for the record"],
                "Cold scorch marks were found near the {asset} at {loc}; nothing is burning and the damage appears old.",
                cause="past fire, timing unknown", asset="{asset}", resources=["inspection"], hint="{loc}",
                note="Fire damage in the past is not a fire now — a category cue without an urgency cue.",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["small active fire in the {asset} at {loc}, we have it contained but it keeps reigniting",
                 "{asset} at {loc} smouldering and relighting, contained for now but not out"],
                "A small fire in the {asset} at {loc} is contained but repeatedly reigniting.",
                cause="smouldering fire", asset="{asset}", resources=["fire response"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["fire in the {asset} at {loc} has reached the fuel drums, evacuating {count} people now",
                 "{asset} fire at {loc} next to stored fuel, pulling {count} people back, risk of it going up"],
                "A fire in the {asset} at {loc} has reached stored fuel drums, prompting evacuation of {count} people.",
                cause="fire reaching fuel storage", asset="{asset}",
                entities=["{count} people evacuating"],
                resources=["fire brigade", "evacuation support"], hint="{loc}",
            ),
        ],
        slots={"asset": ["generator shed", "pump house", "store room", "equipment hut"]},
    ),
    F(
        "fire_alarm_false_positive",
        "FIRE",
        [
            L(
                "LOW", "OPEN",
                ["fire alarm went off at {loc}, checked it, burnt food in the kitchen, standing down",
                 "alarm at {loc} was a false one, someone burnt toast, all clear now"],
                "A fire alarm at {loc} was triggered by burnt food and has been stood down with no fire found.",
                cause="burnt food, false alarm", resources=[], hint="{loc}",
                kind=KIND_FALSE_POSITIVE,
                note="An alarm is not a fire. The stand-down is the whole content of the report.",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["fire alarm at {loc} is genuine, smoke in the plant room, building being cleared",
                 "alarm at {loc} turned out real, there's smoke in the plant room, emptying the building"],
                "A fire alarm at {loc} proved genuine with smoke in the plant room; the building is being cleared.",
                cause="confirmed fire, plant room", resources=["fire response"], hint="{loc}",
                kind=KIND_FALSE_POSITIVE,
                note="Contrast pair: same alarm, opposite outcome, opposite severity.",
            ),
        ],
    ),
    F(
        "fire_horizon_smoke_ambiguous",
        "FIRE",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["can see a column of smoke somewhere past {loc}, no idea how far or what's burning",
                 "big smoke visible beyond {loc}, cant tell distance or source from here"],
                "A column of smoke is visible beyond {loc}; its distance, source and scale are unknown.",
                cause="unknown", resources=["observation"], hint="beyond {loc}",
                kind=KIND_AMBIGUOUS,
                note="Nothing is established except that smoke exists. No entities and no asset may be invented.",
            ),
            L(
                "LOW", "OPEN",
                ["that smoke past {loc} is a controlled burn, confirmed with the farm, nothing needed",
                 "followed up the smoke near {loc}, its a planned burn off, no action"],
                "Smoke observed beyond {loc} was confirmed to be a controlled burn requiring no response.",
                cause="controlled burn, confirmed", resources=[], hint="beyond {loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "fire_extinguished_conflicting",
        "FIRE",
        [
            L(
                "HIGH", "UNKNOWN",
                ["{team} says the fire at {loc} is out, but the other crew says it's still burning at the back, not sure who's right",
                 "conflicting reports on {loc} fire, one crew calls it out, another says flames still visible"],
                "Reports on the fire at {loc} conflict: one crew reports it extinguished while another reports it still burning.",
                cause="fire, status disputed", resources=["confirmation by an incident officer"], hint="{loc}",
                kind=KIND_CONFLICTING,
                note="Disagreement is not resolved by picking a side; status stays UNKNOWN and severity stays conservative.",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["settled the {loc} fire question, it's out at the front but still smouldering at the rear",
                 "checked {loc} myself, front is out, back is smouldering, both crews were half right"],
                "The fire at {loc} is extinguished at the front but still smouldering at the rear.",
                cause="partially extinguished fire", resources=["damping down"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "fire_multi_message_escalation",
        "FIRE",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[0912] smoke seen near {loc}\n[0914] confirmed fire, {asset} alight\n[0917] {count} people unaccounted for, cannot reach the rear",
                 "0840 - burning smell at {loc}\n0847 - flames now visible in the {asset}\n0855 - {count} missing, entry not possible"],
                "Over successive messages a report at {loc} escalated from smoke to a confirmed fire in the {asset} with {count} people unaccounted for and no safe entry.",
                cause="confirmed structure fire", asset="{asset}",
                entities=["{count} people unaccounted for"],
                resources=["fire brigade", "rescue team"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
                note="The correct answer reflects the latest established state, not the first message.",
            ),
            L(
                "LOW", "OPEN",
                ["[1401] smoke reported at {loc}\n[1409] located it, small bin fire\n[1415] out, no damage",
                 "1120 - possible fire {loc}\n1126 - its a small bin fire\n1130 - extinguished, nothing further"],
                "A reported fire at {loc} was located as a small bin fire and extinguished with no damage.",
                cause="bin fire, extinguished", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
                note="Contrast pair: a message sequence that de-escalates must not inherit the alarm of its first line.",
            ),
        ],
        slots={"asset": ["store shed", "workshop", "supply building"]},
    ),
]

FLOODING_FAMILIES = [
    F(
        "flood_depth_ladder",
        "FLOODING",
        [
            L(
                "LOW", "OPEN",
                ["water pooling on the low side of {loc}, ankle deep at worst, draining slowly",
                 "bit of standing water at {loc}, few inches, nothing serious"],
                "Shallow standing water has pooled at {loc} and is draining slowly.",
                cause="rainfall", resources=[], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["water knee deep through {loc} now, moving fast, vehicles can't get down there",
                 "{loc} is under knee deep water and rising, too deep to drive"],
                "Fast-moving knee-deep water is running through {loc}, making it impassable to vehicles.",
                cause="rising floodwater", resources=["pumps", "high-clearance transport"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["water chest high at {loc}, {count} people on roofs, current too strong to wade",
                 "{loc} submerged, {count} stranded above the water line, we need boats not vehicles"],
                "Chest-high floodwater at {loc} has stranded {count} people on rooftops with a current too strong to wade.",
                cause="severe flooding", entities=["{count} people stranded"],
                resources=["rescue boats", "swift water team"], hint="{loc}",
            ),
        ],
    ),
    F(
        "flood_basement_ladder",
        "FLOODING",
        [
            L(
                "MEDIUM", "OPEN",
                ["water coming into the basement at {loc}, slow, maybe an inch so far",
                 "basement at {loc} taking water, not fast, about an inch down there"],
                "Water is entering the basement at {loc} slowly, about an inch deep so far.",
                cause="water ingress", resources=["pump"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["basement flooding at {loc} is now up to the shelving, the {stock} is stored down there",
                 "water in the {loc} basement reached the stock shelves, {stock} at risk"],
                "Flooding in the {loc} basement has reached storage shelving where {stock} is kept.",
                cause="water ingress", entities=[], resources=["pumps", "stock relocation"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["water in the {loc} basement has reached the electrical panel, cutting supply and clearing the building",
                 "flooding at {loc} up to the switchgear, killing the power and getting everyone out"],
                "Floodwater in the {loc} basement has reached the electrical panel, forcing a power cut and building evacuation.",
                cause="floodwater reaching electrical equipment",
                resources=["electrician", "pumps", "evacuation support"], hint="{loc}",
            ),
        ],
        slots={"stock": ["medical supplies", "food stock", "spare radios", "the records"]},
    ),
    F(
        "flood_river_stage_ladder",
        "FLOODING",
        [
            L(
                "LOW", "OPEN",
                ["river at {loc} is up after the rain but still well inside the banks",
                 "water level higher than usual at {loc}, nowhere near the top yet"],
                "The river at {loc} has risen after rain but remains well within its banks.",
                cause="rainfall runoff", resources=["monitoring"], hint="{loc}",
                note="A rise is not a flood. Category cue present, urgency absent.",
            ),
            L(
                "MEDIUM", "OPEN",
                ["river at {loc} over the bank into the fields, not near any houses yet",
                 "water's come over at {loc} onto the low fields, no buildings affected so far"],
                "The river at {loc} has overtopped its bank into fields, with no buildings affected yet.",
                cause="river overtopping", resources=["monitoring"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["river through the houses at {loc}, {count} families cut off on the far side, water still rising",
                 "{loc} flooded through the homes, {count} households isolated, level going up"],
                "The river has flooded homes at {loc}, cutting off {count} households as the water continues rising.",
                cause="river flooding of housing", entities=["{count} households cut off"],
                resources=["rescue boats", "shelter"], hint="{loc}",
            ),
        ],
    ),
    F(
        "flood_seepage_ladder",
        "FLOODING",
        [
            L(
                "LOW", "OPEN",
                ["small amount of seepage through the embankment at {loc}, clear water, been like it for a while",
                 "little bit of water weeping through the bank at {loc}, clear, not new"],
                "Minor clear seepage is present through the embankment at {loc} and appears long-standing.",
                cause="embankment seepage", resources=["monitoring"], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["seepage at the {loc} embankment has increased and it's carrying silt now",
                 "more water coming through the bank at {loc} than before, and it's running muddy"],
                "Seepage through the {loc} embankment has increased and is now carrying silt.",
                cause="increasing embankment seepage", resources=["engineering assessment"], hint="{loc}",
                note="Silt in seepage means material is moving — a genuine escalation cue.",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["the {loc} embankment is slumping with water running through it, everything downstream needs to move now",
                 "bank at {loc} failing, water cutting through, get the downstream side clear immediately"],
                "The embankment at {loc} is slumping with water cutting through it, requiring immediate clearance downstream.",
                cause="embankment failure in progress",
                resources=["evacuation support", "engineering response"], hint="{loc}",
            ),
        ],
    ),
    F(
        "flood_hearsay_ambiguous",
        "FLOODING",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["someone came in saying {loc} is flooded, they heard it from someone else, no details at all",
                 "second hand report that {loc} has water, no depth, no time, nobody's seen it themselves"],
                "A second-hand report claims flooding at {loc}, with no depth, timing or direct observation available.",
                cause="unconfirmed", resources=["verification"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
                note="Hearsay establishes that a claim exists, not that the thing is true.",
            ),
            L(
                "HIGH", "BLOCKED",
                ["checked {loc} ourselves, it is flooded, water over the road and into the first row of houses",
                 "confirmed {loc} flooding directly, road under water and houses taking it"],
                "Direct observation confirms flooding at {loc}, with water over the road and entering houses.",
                cause="confirmed flooding", resources=["pumps", "shelter"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "flood_depth_conflicting",
        "FLOODING",
        [
            L(
                "HIGH", "UNKNOWN",
                ["one report says the crossing at {loc} is knee deep, another says it's over the bonnet, can't reconcile them",
                 "we have two depths for {loc}, knee deep and roof height, no way to tell which is current"],
                "Reported depths for the crossing at {loc} conflict sharply and cannot be reconciled.",
                cause="flooding, depth disputed", resources=["direct measurement"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["measured {loc} crossing, it's thigh deep, both earlier reports were from different hours",
                 "went and looked at {loc}, thigh deep now, the earlier numbers were just taken at different times"],
                "Direct measurement puts the crossing at {loc} at thigh depth; earlier conflicting reports were taken at different times.",
                cause="flooding, depth measured", resources=["high-clearance transport"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "flood_receding_info",
        "FLOODING",
        [
            L(
                "LOW", "OPEN",
                ["water's gone down at {loc}, road's usable again, just silt left to clear",
                 "{loc} has drained, passable now, only mud on the surface"],
                "Floodwater at {loc} has receded and the road is usable, leaving only silt to clear.",
                cause="floodwater receding", resources=["road cleaning"], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["water down at {loc} but the surface has been undercut, only light vehicles should use it",
                 "{loc} drained, however the road edge is washed out underneath, light traffic only"],
                "Floodwater at {loc} has receded but the road surface is undercut, limiting it to light vehicles.",
                cause="flood damage to road surface", resources=["road inspection"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
    ),
    F(
        "flood_multi_message_rise",
        "FLOODING",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[1830] water at the door step {loc}\n[1902] inside the houses now\n[1935] {count} people on the upper floor, can't get out",
                 "1710 water at the gate {loc}\n1748 through the ground floor\n1820 {count} stuck upstairs, no route out"],
                "Successive messages track floodwater at {loc} rising from doorstep to ground floor, leaving {count} people trapped upstairs.",
                cause="rapidly rising floodwater", entities=["{count} people trapped upstairs"],
                resources=["rescue boats"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["[0600] water rising at {loc}\n[0730] holding at the kerb\n[0900] dropping now, nothing entered the buildings",
                 "0540 level climbing {loc}\n0705 steady at the kerb line\n0840 falling, no buildings affected"],
                "Floodwater at {loc} rose to the kerb, held, and is now falling with no buildings affected.",
                cause="floodwater peaked and receding", resources=["monitoring"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

SEVERE_WEATHER_FAMILIES = [
    F(
        "weather_wind_ladder",
        "SEVERE_WEATHER",
        [
            L(
                "LOW", "OPEN",
                ["breezy at {loc}, bins over, nothing that matters",
                 "wind picking up at {loc}, a few light things blown about, no damage"],
                "Gusty wind at {loc} has moved light objects without causing damage.",
                cause="wind", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["wind at {loc} taking sheets off the roofs, one shelter's flapping badly",
                 "gusts at {loc} lifting roof sheeting, shelters struggling"],
                "Wind at {loc} is lifting roof sheeting and straining shelters.",
                cause="high wind", resources=["roof securing"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["wind at {loc} has flattened {count} shelters, people moving into the hall, still gusting hard",
                 "{count} tents down at {loc} from the wind, relocating people, it hasn't eased"],
                "High wind at {loc} has flattened {count} shelters, forcing relocation while gusts continue.",
                cause="destructive wind", entities=["{count} shelters destroyed"],
                resources=["temporary shelter"], hint="{loc}",
            ),
        ],
    ),
    F(
        "weather_rain_ladder",
        "SEVERE_WEATHER",
        [
            L(
                "MEDIUM", "OPEN",
                ["heavy rain at {loc} for a few hours now, ground's soaking but nothing's flooded",
                 "steady heavy rain over {loc}, ground saturated, no water problems yet"],
                "Several hours of heavy rain at {loc} have saturated the ground without causing flooding.",
                cause="sustained heavy rain", resources=["monitoring"], hint="{loc}",
                note="Weather as the hazard, not its downstream effects — that keeps it out of FLOODING.",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["rain at {loc} hasn't stopped in {hours} hours, slopes are running, we're watching the hillside",
                 "{hours} hours of rain at {loc}, water running off the slopes, hill looks unstable"],
                "Rain at {loc} has continued for {hours} hours with runoff from slopes raising slope stability concern.",
                cause="prolonged heavy rain", resources=["slope monitoring"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["rain at {loc} is torrential, visibility near zero and the whole slope above the camp is moving",
                 "torrential rain {loc}, can't see, the hillside above us is shifting, moving people out"],
                "Torrential rain at {loc} has reduced visibility to near zero as the slope above the camp begins moving.",
                cause="torrential rain destabilising a slope",
                resources=["evacuation support"], hint="{loc}",
            ),
        ],
    ),
    F(
        "weather_hail_ladder",
        "SEVERE_WEATHER",
        [
            L(
                "LOW", "OPEN",
                ["small hail at {loc} for a couple of minutes, nothing damaged",
                 "bit of hail passed over {loc}, tiny stones, no harm done"],
                "Brief small hail at {loc} caused no damage.",
                cause="hail", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["hail at {loc} big enough to dent the vehicles and hole two tarpaulins",
                 "decent sized hail at {loc}, vehicle panels dented, couple of covers holed"],
                "Hail at {loc} has dented vehicles and holed tarpaulins.",
                cause="large hail", resources=["tarpaulin replacement"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["hail at {loc} has come through the roof panels, {count} people took hits getting inside",
                 "heavy hail at {loc} broke through roofing, {count} injured on the way to cover"],
                "Hail at {loc} has penetrated roof panels, injuring {count} people seeking cover.",
                cause="severe hail", entities=["{count} people injured"],
                resources=["first aid", "roof repair"], hint="{loc}",
            ),
        ],
    ),
    F(
        "weather_storm_timing_ladder",
        "SEVERE_WEATHER",
        [
            L(
                "LOW", "OPEN",
                ["storm expected near {loc} in about two days, plenty of time, just noting it",
                 "theres weather coming for {loc} but not for a couple of days yet"],
                "A storm is expected near {loc} in approximately two days.",
                cause="forecast storm, distant", resources=[], hint="{loc}",
                note="Same storm, different lead time — the timing is what moves severity here.",
            ),
            L(
                "MEDIUM", "OPEN",
                ["storm now expected at {loc} within {hours} hours, we're tying things down",
                 "weather front reaching {loc} in {hours} hours, securing equipment"],
                "A storm is now expected at {loc} within {hours} hours and equipment is being secured.",
                cause="approaching storm", resources=["equipment securing"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["storm is on top of {loc} now, nobody can move outside, {count} people sheltering in place",
                 "the storm has hit {loc}, outdoor movement impossible, {count} sheltering where they are"],
                "A storm has reached {loc}, making outdoor movement impossible with {count} people sheltering in place.",
                cause="storm at full strength", entities=["{count} people sheltering in place"],
                resources=["shelter support"], hint="{loc}",
            ),
        ],
    ),
    F(
        "weather_forecast_ambiguous",
        "SEVERE_WEATHER",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["heard there's bad weather coming for {loc} but nobody can say what kind or when",
                 "word going round about weather at {loc}, no detail on what or when, can't verify"],
                "An unverified report warns of bad weather at {loc} without specifying its nature or timing.",
                cause="unconfirmed weather warning", resources=["verification"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
            L(
                "LOW", "OPEN",
                ["chased up the {loc} weather talk, it's just a wind advisory, nothing significant",
                 "the {loc} weather rumour is only a routine wind advisory, no action needed"],
                "The weather warning for {loc} was confirmed to be a routine wind advisory requiring no action.",
                cause="routine wind advisory", resources=[], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "weather_conflicting_severity",
        "SEVERE_WEATHER",
        [
            L(
                "HIGH", "UNKNOWN",
                ["{team} at {loc} says conditions are unworkable, another group says it's fine, both are on site",
                 "getting opposite accounts of {loc} conditions from two teams both standing in it"],
                "Two teams on site at {loc} give opposite accounts of whether conditions are workable.",
                cause="severe weather, extent disputed", resources=["on-site assessment"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["sorted the {loc} disagreement, exposed side is unworkable, sheltered side is fine",
                 "both {loc} reports were right, it's bad on the exposed side and calm behind the ridge"],
                "Conditions at {loc} differ by aspect: the exposed side is unworkable while the sheltered side is calm.",
                cause="severe weather, localised", resources=["work restricted to sheltered side"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "weather_passed_info",
        "SEVERE_WEATHER",
        [
            L(
                "LOW", "OPEN",
                ["weather's cleared at {loc}, sun out, normal operations resuming",
                 "storm has passed {loc}, all clear, back to normal"],
                "The storm has passed {loc} and normal operations are resuming.",
                cause="weather passed", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["storm's passed {loc} but it's left debris everywhere, restricting movement until it's cleared",
                 "weather over at {loc}, debris across the site, movement limited till cleared"],
                "The storm has passed {loc} but left debris restricting movement until cleared.",
                cause="post-storm debris", resources=["debris clearance"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
    ),
    F(
        "weather_multi_message_front",
        "SEVERE_WEATHER",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[1500] wind building at {loc}\n[1540] gusts taking roofing off\n[1615] {count} shelters gone, people in the open",
                 "1420 wind rising {loc}\n1505 roofs lifting\n1545 {count} shelters destroyed, people exposed"],
                "Successive messages track wind at {loc} escalating until {count} shelters were destroyed, leaving people exposed.",
                cause="destructive wind", entities=["{count} shelters destroyed"],
                resources=["emergency shelter"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[0900] wind warning for {loc}\n[1100] gusts lighter than expected\n[1300] warning lifted, nothing damaged",
                 "0830 warning issued {loc}\n1030 milder than forecast\n1230 stood down, no damage"],
                "A wind warning for {loc} was lifted after conditions proved milder than forecast, with no damage.",
                cause="wind warning, stood down", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

EARTHQUAKE_FAMILIES = [
    F(
        "quake_shaking_ladder",
        "EARTHQUAKE",
        [
            L(
                "LOW", "OPEN",
                ["felt a small tremor at {loc}, a few seconds, nothing moved",
                 "brief shake at {loc}, barely noticed it, no damage anywhere"],
                "A brief minor tremor was felt at {loc} with no damage.",
                cause="minor seismic tremor", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["decent shake at {loc}, stuff off the shelves and a crack in the render, structure looks sound",
                 "tremor at {loc} knocked things down and cracked the plaster, building seems ok"],
                "A tremor at {loc} displaced items and cracked render, with the structure appearing sound.",
                cause="seismic tremor", resources=["structural inspection"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["strong quake at {loc}, part of the {asset} has come down with {count} people inside it",
                 "big shake at {loc}, {asset} partially collapsed, {count} people in there when it went"],
                "A strong earthquake at {loc} partially collapsed the {asset} with {count} people inside.",
                cause="earthquake structural collapse", asset="{asset}",
                entities=["{count} people inside the collapsed structure"],
                resources=["search and rescue", "ambulance"], hint="{loc}",
            ),
        ],
        slots={"asset": ["dormitory block", "store building", "clinic wing", "school hall"]},
    ),
    F(
        "quake_aftershock_ladder",
        "EARTHQUAKE",
        [
            L(
                "LOW", "OPEN",
                ["small aftershock at {loc}, nothing new came down",
                 "another little shake at {loc}, no additional damage"],
                "A small aftershock at {loc} caused no additional damage.",
                cause="aftershock", resources=[], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["aftershock at {loc} has opened the cracks further in the {asset}, pulling everyone out of it",
                 "shake at {loc} widened the existing cracks in the {asset}, evacuating the building"],
                "An aftershock at {loc} widened existing cracks in the {asset}, prompting its evacuation.",
                cause="aftershock worsening existing damage", asset="{asset}",
                resources=["structural engineers"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["aftershock brought the damaged {asset} at {loc} down, {count} people were working around it",
                 "the weakened {asset} at {loc} collapsed in the aftershock with {count} people nearby"],
                "An aftershock collapsed the already-damaged {asset} at {loc} with {count} people working nearby.",
                cause="collapse of earthquake-damaged structure", asset="{asset}",
                entities=["{count} people nearby at the time"],
                resources=["search and rescue"], hint="{loc}",
            ),
        ],
        slots={"asset": ["damaged wall", "store building", "stair tower", "gable end"]},
    ),
    F(
        "quake_damage_survey_ladder",
        "EARTHQUAKE",
        [
            L(
                "LOW", "OPEN",
                ["walked {loc} after the tremor, cosmetic cracks only, everything's usable",
                 "survey of {loc} done, just surface cracking, all buildings fine to use"],
                "A post-tremor survey of {loc} found only cosmetic cracking with all buildings usable.",
                cause="minor earthquake damage", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["survey at {loc} found {count} buildings with structural cracks, restricting those until checked",
                 "{count} buildings at {loc} have structural cracking, keeping people out of them for now"],
                "A survey at {loc} found structural cracking in {count} buildings, which are restricted pending inspection.",
                cause="earthquake structural damage", entities=["{count} buildings affected"],
                resources=["structural engineers"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["survey at {loc} says the {asset} is unsafe and it's the only one holding the water tanks",
                 "{asset} at {loc} assessed unsafe, and the tanks sit on it, closing the area off"],
                "A survey found the {asset} at {loc} unsafe while it supports the water tanks, closing the area.",
                cause="earthquake damage to a load-bearing structure", asset="{asset}",
                resources=["structural engineers", "alternative water storage"], hint="{loc}",
            ),
        ],
        slots={"asset": ["support frame", "tank platform", "roof structure"]},
    ),
    F(
        "quake_utility_damage_ladder",
        "EARTHQUAKE",
        [
            L(
                "MEDIUM", "OPEN",
                ["tremor at {loc} cracked a water pipe, losing some supply but it's isolated",
                 "shake at {loc} broke a pipe, some water lost, valve shut off"],
                "A tremor at {loc} cracked a water pipe, causing isolated supply loss.",
                cause="earthquake damage to pipework", resources=["plumbing repair"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["the quake at {loc} has broken the main feed, no water to the {facility} at all now",
                 "main water line at {loc} broken by the shake, {facility} has nothing coming in"],
                "The earthquake at {loc} broke the main water feed, cutting supply to the {facility} entirely.",
                cause="earthquake damage to the main supply",
                resources=["water tankering", "pipe repair"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["quake at {loc} has ruptured the gas line next to the {facility}, smell is strong, clearing {count} people out",
                 "gas main ruptured at {loc} by the {facility} after the shake, moving {count} people away"],
                "An earthquake at {loc} ruptured a gas line beside the {facility}, forcing {count} people to be moved.",
                cause="earthquake rupture of a gas line",
                entities=["{count} people evacuated"],
                resources=["gas isolation", "evacuation support"], hint="{loc}",
            ),
        ],
        slots={"facility": ["clinic", "kitchen block", "main store", "dormitory"]},
    ),
    F(
        "quake_felt_unconfirmed_ambiguous",
        "EARTHQUAKE",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["something shook at {loc}, could have been a quake or the quarry blasting, nobody's sure",
                 "felt a jolt at {loc}, might be seismic, might be the blasting, no way to tell here"],
                "A jolt was felt at {loc} that may be seismic or from quarry blasting; the cause is undetermined.",
                cause="undetermined", resources=["verification"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
                note="Cause genuinely unknown: the report must not assert an earthquake it cannot establish.",
            ),
            L(
                "LOW", "OPEN",
                ["the {loc} jolt was quarry blasting, confirmed with the site, not seismic",
                 "checked the {loc} shake, it was blasting at the quarry, nothing seismic"],
                "The jolt felt at {loc} was confirmed as quarry blasting rather than seismic activity.",
                cause="quarry blasting, confirmed", resources=[], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "quake_casualty_conflicting",
        "EARTHQUAKE",
        [
            L(
                "HIGH", "UNKNOWN",
                ["numbers from {loc} don't agree, one says everyone's accounted for, another says {count} are missing",
                 "conflicting counts at {loc}, all clear from one source and {count} unaccounted from another"],
                "Accounts from {loc} conflict on whether everyone is accounted for or {count} people are missing.",
                cause="earthquake, casualty status disputed",
                resources=["roll call", "search team"], hint="{loc}",
                kind=KIND_CONFLICTING,
                note="Conflicting counts must not be averaged or silently resolved.",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["roll call at {loc} is complete, everyone's accounted for, the missing {count} were on the other shift",
                 "{loc} headcount done, nobody missing, the {count} people were just off site"],
                "A completed roll call at {loc} accounts for everyone; the {count} reported missing were off site.",
                cause="earthquake, all personnel accounted for",
                resources=["structural inspection"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "quake_all_clear_info",
        "EARTHQUAKE",
        [
            L(
                "LOW", "OPEN",
                ["{loc} cleared after the tremor, buildings checked and signed off, back to normal",
                 "inspection finished at {loc}, everything passed, reoccupying the buildings"],
                "Buildings at {loc} have been inspected and cleared after the tremor, and are being reoccupied.",
                cause="post-tremor inspection completed", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["{loc} mostly cleared but the {asset} stays shut until an engineer sees it",
                 "most of {loc} is signed off, the {asset} remains closed pending an engineer"],
                "Most of {loc} has been cleared after the tremor, but the {asset} remains closed pending engineering review.",
                cause="post-tremor inspection, one structure outstanding", asset="{asset}",
                resources=["structural engineers"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
        slots={"asset": ["store building", "water tower", "stair block"]},
    ),
    F(
        "quake_multi_message_sequence",
        "EARTHQUAKE",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[0204] strong shaking at {loc}\n[0206] {asset} down\n[0215] {count} people unaccounted for in it",
                 "0330 big tremor {loc}\n0333 {asset} collapsed\n0341 {count} missing inside"],
                "Successive messages report strong shaking at {loc}, collapse of the {asset}, and {count} people unaccounted for inside.",
                cause="earthquake structural collapse", asset="{asset}",
                entities=["{count} people unaccounted for"],
                resources=["search and rescue", "ambulance"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[1112] tremor felt at {loc}\n[1140] walked the site, nothing moved\n[1210] no damage found anywhere",
                 "0915 shake at {loc}\n0940 site walked\n1005 nothing damaged"],
                "A tremor felt at {loc} was followed by a site walk that found no damage.",
                cause="minor tremor, no damage", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
        slots={"asset": ["dormitory wall", "store building", "clinic annexe"]},
    ),
]

HAZARD_FAMILIES = (
    FIRE_FAMILIES + FLOODING_FAMILIES + SEVERE_WEATHER_FAMILIES + EARTHQUAKE_FAMILIES
)
