"""Scenario families for INFRASTRUCTURE, POWER, COMMUNICATIONS,
ROAD_BLOCKAGE and RESOURCE_SHORTAGE.

Two Phase 1 gaps are closed deliberately here: INFRASTRUCTURE had no LOW and
no CRITICAL example at all, and RESOURCE_SHORTAGE had no LOW. Both now span
the full range, because both genuinely do — a hairline crack and a partial
collapse are the same category, and so are "three days of water left" and
"two hours of water left".
"""

from __future__ import annotations

from .schema import (
    F,
    KIND_AMBIGUOUS,
    KIND_CONFLICTING,
    KIND_FALSE_POSITIVE,
    KIND_INFO,
    KIND_MULTI_MESSAGE,
    L,
)

INFRASTRUCTURE_FAMILIES = [
    F(
        "infra_crack_ladder",
        "INFRASTRUCTURE",
        [
            L(
                "LOW", "OPEN",
                ["hairline crack in the {asset} at {loc}, same as it's been for months, logging it",
                 "thin crack on the {asset} at {loc}, not changed, recording for the file"],
                "A stable hairline crack in the {asset} at {loc} has been recorded.",
                cause="long-standing minor cracking", asset="{asset}",
                resources=["periodic monitoring"], hint="{loc}",
                note="INFRASTRUCTURE at its low end — damage that is real, recorded, and not urgent.",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["the crack in the {asset} at {loc} has widened since last week and there's dust coming out of it",
                 "{asset} crack at {loc} is bigger than it was, and it's shedding material"],
                "A crack in the {asset} at {loc} has widened and is shedding material.",
                cause="progressive structural cracking", asset="{asset}",
                resources=["structural engineers"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["part of the {asset} at {loc} has come down and {count} people were working underneath it",
                 "{asset} at {loc} partially collapsed with {count} people right below"],
                "Part of the {asset} at {loc} has collapsed with {count} people working directly beneath it.",
                cause="structural collapse", asset="{asset}",
                entities=["{count} people beneath the collapse"],
                resources=["search and rescue", "ambulance", "structural engineers"], hint="{loc}",
            ),
        ],
        slots={"asset": ["retaining wall", "gable wall", "support column", "parapet"]},
    ),
    F(
        "infra_roof_ladder",
        "INFRASTRUCTURE",
        [
            L(
                "LOW", "OPEN",
                ["small leak in the {loc} roof, bucket under it, not spreading",
                 "drip through the roof at {loc}, contained with a bucket"],
                "A small contained roof leak at {loc} is not spreading.",
                cause="roof leak", resources=["roof repair"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["the {loc} roof is sagging where the water's collected, we've moved everyone out from under it",
                 "roof at {loc} bowing under standing water, cleared the area beneath"],
                "The roof at {loc} is sagging under accumulated water and the area beneath has been cleared.",
                cause="roof loading from standing water",
                resources=["structural engineers", "water removal"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["roof section at {loc} has come in over the {facility}, {count} people were in there",
                 "part of the {loc} roof collapsed into the {facility} with {count} inside"],
                "A roof section at {loc} has collapsed into the {facility} with {count} people inside.",
                cause="roof collapse", asset="{facility}",
                entities=["{count} people inside at collapse"],
                resources=["search and rescue", "ambulance"], hint="{loc}",
            ),
        ],
        slots={"facility": ["dormitory", "store room", "dining hall", "clinic"]},
    ),
    F(
        "infra_water_system_ladder",
        "INFRASTRUCTURE",
        [
            L(
                "MEDIUM", "OPEN",
                ["the water tank at {loc} is leaking from a seam, losing maybe a bucket an hour",
                 "slow leak on the {loc} tank seam, small but constant loss"],
                "The water tank at {loc} is leaking slowly from a seam.",
                cause="tank seam leak", asset="water tank", resources=["tank repair"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["the {loc} tank is emptying fast through a split, we'll lose the whole supply in {hours} hours",
                 "split in the {loc} tank draining it, {hours} hours of supply left at this rate"],
                "A split in the tank at {loc} is draining supply, with {hours} hours remaining at the current rate.",
                cause="tank failure", asset="water tank",
                resources=["tank repair", "alternative water storage"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["the tank platform at {loc} is leaning over the {facility} and there are {count} people under it",
                 "{loc} tank stand tilting above the {facility}, {count} people below"],
                "The water tank platform at {loc} is leaning over the {facility} with {count} people beneath it.",
                cause="failure of a tank support structure", asset="tank platform",
                entities=["{count} people beneath the platform"],
                resources=["structural engineers", "area clearance"], hint="{loc}",
            ),
        ],
        slots={"facility": ["dining area", "dormitory", "store", "clinic entrance"]},
    ),
    F(
        "infra_bridge_ladder",
        "INFRASTRUCTURE",
        [
            L(
                "LOW", "OPEN",
                ["the footbridge at {loc} creaks under load, been doing it for years, no movement in it",
                 "{loc} footbridge makes noise when you cross, nothing's shifted, longstanding"],
                "The footbridge at {loc} creaks under load with no observed movement, a long-standing condition.",
                cause="long-standing noise under load", asset="footbridge",
                resources=["routine inspection"], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["the {loc} bridge deck is moving visibly when trucks cross, limiting it to light vehicles",
                 "visible deck movement on the {loc} bridge under heavy loads, light vehicles only now"],
                "The bridge deck at {loc} moves visibly under heavy vehicles and is now limited to light traffic.",
                cause="deck movement under load", asset="bridge deck",
                resources=["structural assessment", "load restriction"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["the {loc} bridge abutment has shifted and the deck's dropped at one end, closing it completely",
                 "abutment movement at the {loc} bridge has dropped the deck, bridge shut"],
                "The bridge abutment at {loc} has shifted, dropping one end of the deck and closing the bridge.",
                cause="abutment movement", asset="bridge abutment",
                resources=["structural engineers", "alternative route"], hint="{loc}",
            ),
        ],
    ),
    F(
        "infra_age_unknown_ambiguous",
        "INFRASTRUCTURE",
        [
            L(
                "MEDIUM", "RESTRICTED",
                ["found damage to the {asset} at {loc}, no idea whether it's new or been there for years",
                 "{asset} at {loc} is damaged, can't tell if it happened recently or long ago"],
                "Damage to the {asset} at {loc} has been found, with no way to establish when it occurred.",
                cause="damage of unknown age", asset="{asset}",
                resources=["structural inspection"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
                note="Whether this is urgent depends entirely on whether it is progressing, which is unknown.",
            ),
            L(
                "HIGH", "BLOCKED",
                ["the {asset} damage at {loc} is new, it wasn't there on yesterday's walk round",
                 "confirmed the {asset} damage at {loc} is recent, yesterday's check was clear"],
                "Damage to the {asset} at {loc} is confirmed recent, having been absent the previous day.",
                cause="new structural damage", asset="{asset}",
                resources=["structural engineers"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
        slots={"asset": ["retaining wall", "support beam", "stair structure"]},
    ),
    F(
        "infra_assessment_conflicting",
        "INFRASTRUCTURE",
        [
            L(
                "HIGH", "UNKNOWN",
                ["two assessments of the {loc} {asset} disagree, one says safe to use and one says condemn it",
                 "conflicting verdicts on the {asset} at {loc}, safe versus unsafe, both from people who looked"],
                "Two assessments of the {asset} at {loc} disagree on whether it is safe to use.",
                cause="structural condition disputed", asset="{asset}",
                resources=["independent structural assessment"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["the {loc} {asset} verdicts are reconciled, safe for people but not for stored load",
                 "settled the {asset} question at {loc}, fine for occupancy, not for storage weight"],
                "Assessments of the {asset} at {loc} are reconciled: safe for occupancy but not for stored load.",
                cause="structural capacity limited", asset="{asset}",
                resources=["load restriction", "alternative storage"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
        slots={"asset": ["upper floor", "store building", "walkway"]},
    ),
    F(
        "infra_inspection_cleared_info",
        "INFRASTRUCTURE",
        [
            L(
                "LOW", "OPEN",
                ["the {asset} at {loc} was reported unsafe, inspected it, it's sound, back in use",
                 "checked the {asset} at {loc} after the report, no problem found, reopened"],
                "The {asset} at {loc}, reported unsafe, was inspected, found sound, and returned to use.",
                cause="reported damage not substantiated", asset="{asset}",
                resources=[], hint="{loc}",
                kind=KIND_FALSE_POSITIVE,
            ),
            L(
                "HIGH", "BLOCKED",
                ["inspection of the {asset} at {loc} found worse than reported, taking it out of use entirely",
                 "the {asset} at {loc} is in worse condition than the report said, closing it"],
                "Inspection found the {asset} at {loc} in worse condition than reported, and it has been taken out of use.",
                cause="structural damage worse than reported", asset="{asset}",
                resources=["structural engineers", "alternative facilities"], hint="{loc}",
                kind=KIND_FALSE_POSITIVE,
            ),
        ],
        slots={"asset": ["walkway", "store building", "upper floor", "access stair"]},
    ),
    F(
        "infra_multi_message_wall",
        "INFRASTRUCTURE",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[1320] crack noticed in the {loc} wall\n[1355] it's opening, dust falling\n[1410] wall down, {count} people were beside it",
                 "0710 wall crack {loc}\n0745 widening quickly\n0800 collapsed, {count} people alongside"],
                "Messages from {loc} track a wall crack widening to collapse with {count} people alongside it.",
                cause="progressive failure to collapse", asset="wall",
                entities=["{count} people beside the collapse"],
                resources=["search and rescue", "ambulance"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["[0815] crack seen in the {loc} wall\n[0900] measured, no change in an hour\n[1000] still stable, propping it anyway",
                 "1420 crack {loc} wall\n1500 no movement measured\n1600 stable, props going in"],
                "A wall crack at {loc} was measured over successive checks, showed no movement, and is being propped as a precaution.",
                cause="stable structural cracking", asset="wall",
                resources=["propping", "structural monitoring"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

POWER_FAMILIES = [
    F(
        "power_outage_scope_ladder",
        "POWER",
        [
            L(
                "LOW", "OPEN",
                ["lights flickering in the {loc} office, everything still working",
                 "bit of flicker on the power at {loc}, nothing's gone off"],
                "Power at {loc} is flickering without any loss of supply.",
                cause="intermittent supply", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["power's off across {loc}, everything non-essential is down, no one at risk",
                 "outage covering {loc}, nothing critical affected, people are fine"],
                "A power outage across {loc} has taken non-essential services down with no one at risk.",
                cause="power outage", resources=["power restoration"], hint="{loc}",
            ),
            L(
                "CRITICAL", "OPEN",
                ["power's gone at the {loc} clinic and {count} patients are on equipment that needs it",
                 "outage at the {loc} clinic with {count} people on powered equipment"],
                "A power outage at the {loc} clinic affects {count} patients dependent on powered equipment.",
                cause="power outage affecting life-critical equipment",
                entities=["{count} patients on powered equipment"],
                resources=["generator", "immediate power restoration"], hint="{loc}",
            ),
        ],
    ),
    F(
        "power_fuel_ladder",
        "POWER",
        [
            L(
                "LOW", "OPEN",
                ["generator at {loc} refuelled, good for several days now",
                 "topped up the {loc} generator, plenty in it"],
                "The generator at {loc} has been refuelled with several days of capacity.",
                cause="routine refuelling", asset="generator", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["{loc} generator down to about {hours} hours of fuel, need to sort a delivery",
                 "roughly {hours} hours of generator fuel left at {loc}, delivery needed"],
                "The generator at {loc} has approximately {hours} hours of fuel remaining.",
                cause="depleting generator fuel", asset="generator",
                resources=["fuel delivery"], hint="{loc}",
            ),
            L(
                "CRITICAL", "OPEN",
                ["{loc} generator has minutes of fuel and it's the only supply to the cold store and the clinic",
                 "generator at {loc} about to run dry, it's all that's powering the clinic and cold store"],
                "The generator at {loc} has minutes of fuel remaining and is the sole supply to the clinic and cold store.",
                cause="imminent generator fuel exhaustion", asset="generator",
                resources=["immediate fuel delivery"], hint="{loc}",
            ),
        ],
    ),
    F(
        "power_line_ladder",
        "POWER",
        [
            L(
                "MEDIUM", "OPEN",
                ["power line sagging low across the field at {loc}, nobody goes through there",
                 "line hanging low at {loc} over open ground, no access that way"],
                "A power line is sagging low over open ground at {loc} where there is no access.",
                cause="line sag", asset="power line", resources=["line repair"], hint="{loc}",
            ),
            L(
                "HIGH", "RESTRICTED",
                ["line's down in the field at {loc}, no one near it but it may still be live",
                 "downed line at {loc} in open ground, possibly still energised, keeping people off"],
                "A power line is down on open ground at {loc} and may still be live.",
                cause="downed power line", asset="power line",
                resources=["power isolation", "line repair"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["live line down across the road at {loc}, sparking, and {count} people are on the wrong side of it",
                 "power line down and arcing across the {loc} road with {count} people cut off behind it"],
                "A live power line is down and arcing across the road at {loc}, cutting off {count} people.",
                cause="live downed line across a road", asset="power line",
                entities=["{count} people cut off"],
                resources=["power isolation", "road closure"], hint="{loc}",
            ),
        ],
    ),
    F(
        "power_equipment_ladder",
        "POWER",
        [
            L(
                "LOW", "OPEN",
                ["the {loc} distribution board is humming a bit, no heat, no smell, keeping an eye on it",
                 "slight hum from the board at {loc}, cool to touch, monitoring"],
                "The distribution board at {loc} is humming with no heat or smell, and is being monitored.",
                cause="audible noise from equipment", asset="distribution board",
                resources=["monitoring"], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["the {loc} board is running hot and smells of burning plastic, we've isolated it",
                 "board at {loc} overheating with a burning smell, supply isolated"],
                "The distribution board at {loc} was overheating with a burning smell and has been isolated.",
                cause="overheating electrical equipment", asset="distribution board",
                resources=["electrician"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["the {loc} switchgear is arcing behind the panel, cleared the room and killed what we could",
                 "arcing inside the {loc} switchgear, room evacuated, supply cut where possible"],
                "Switchgear at {loc} is arcing behind its panel; the room has been cleared and supply cut where possible.",
                cause="arcing switchgear", asset="switchgear",
                resources=["electrician", "power isolation"], hint="{loc}",
            ),
        ],
    ),
    F(
        "power_cause_ambiguous",
        "POWER",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["power's off at {loc}, no idea if it's us, the supply, or something broken somewhere",
                 "{loc} has no power and we can't tell whether it's our equipment or the incoming supply"],
                "Power is off at {loc} with no determination yet of whether the fault is local or in the incoming supply.",
                cause="undetermined", resources=["electrical fault finding"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
            L(
                "LOW", "OPEN",
                ["found the {loc} power fault, tripped breaker, reset it and everything's back",
                 "{loc} outage was a tripped breaker, reset and restored"],
                "The power fault at {loc} was a tripped breaker, now reset and supply restored.",
                cause="tripped breaker", resources=[], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "power_restoration_conflicting",
        "POWER",
        [
            L(
                "HIGH", "UNKNOWN",
                ["we've been told power at {loc} comes back in an hour and also not for {hours} hours, planning is impossible",
                 "two restoration times for {loc}, one hour or {hours} hours, can't plan against either"],
                "Restoration estimates for power at {loc} conflict between one hour and {hours} hours.",
                cause="power outage with disputed restoration time",
                resources=["confirmed restoration estimate", "generator contingency"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["{loc} restoration confirmed at {hours} hours, the shorter estimate was for a different sector",
                 "power back at {loc} in {hours} hours, the other figure belonged to another area"],
                "Power restoration at {loc} is confirmed for {hours} hours; the shorter estimate applied to another sector.",
                cause="power outage, restoration confirmed",
                resources=["generator cover for the interim"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "power_restored_info",
        "POWER",
        [
            L(
                "LOW", "OPEN",
                ["power back on across {loc}, everything's come up normally",
                 "supply restored at {loc}, all systems back"],
                "Power has been restored across {loc} with all systems operating normally.",
                cause="supply restored", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["power's back at {loc} but it keeps dropping every few minutes, running the generator alongside",
                 "supply restored at {loc} though unstable, dropping repeatedly, generator kept running"],
                "Power at {loc} has been restored but is unstable and repeatedly dropping, with the generator kept running.",
                cause="unstable restored supply", resources=["supply stabilisation"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
    ),
    F(
        "power_multi_message_failure",
        "POWER",
        [
            L(
                "CRITICAL", "OPEN",
                ["[2210] mains lost at {loc}\n[2212] generator started\n[2350] generator failed, {count} patients on equipment with nothing",
                 "0140 supply lost {loc}\n0142 generator running\n0305 generator down, {count} on powered equipment"],
                "Messages from {loc} track loss of mains, generator start, and generator failure leaving {count} patients on powered equipment without supply.",
                cause="successive failure of mains and generator",
                entities=["{count} patients on powered equipment"],
                resources=["replacement generator", "immediate power restoration"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[1500] power off at {loc}\n[1505] generator up\n[1540] mains back, generator shut down",
                 "0920 outage {loc}\n0924 generator online\n0950 mains restored, generator off"],
                "A power outage at {loc} was covered by the generator until mains supply was restored.",
                cause="short outage covered by generator", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

COMMUNICATIONS_FAMILIES = [
    F(
        "comms_coverage_ladder",
        "COMMUNICATIONS",
        [
            L(
                "LOW", "OPEN",
                ["signal's patchy at {loc}, drops now and then but messages get through eventually",
                 "weak coverage at {loc}, occasional drops, still usable"],
                "Mobile coverage at {loc} is patchy with occasional drops but remains usable.",
                cause="weak coverage", resources=[], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["no mobile signal at all across {loc} now, radio still works",
                 "mobile network down over {loc}, we still have radio"],
                "Mobile coverage has failed across {loc}, with radio still available.",
                cause="mobile network outage", resources=["network restoration"], hint="{loc}",
            ),
            L(
                "CRITICAL", "UNKNOWN",
                ["everything's down at {loc}, no mobile, no radio, and {team} is out there with no way to reach them",
                 "total comms loss at {loc}, mobile and radio both gone, {team} unreachable in the field"],
                "All communications have failed at {loc} with {team} in the field and unreachable.",
                cause="total communications failure",
                entities=["1 field team unreachable"],
                resources=["satellite communications", "physical runner"], hint="{loc}",
            ),
        ],
    ),
    F(
        "comms_repeater_ladder",
        "COMMUNICATIONS",
        [
            L(
                "MEDIUM", "OPEN",
                ["the {loc} repeater is dropping in and out, conversations keep breaking up",
                 "repeater at {loc} intermittent, calls keep cutting"],
                "The repeater at {loc} is intermittent, causing calls to break up.",
                cause="intermittent repeater fault", asset="repeater",
                resources=["repeater maintenance"], hint="{loc}",
            ),
            L(
                "HIGH", "OPEN",
                ["{loc} repeater is completely down, we're on handhelds and the range barely covers the site",
                 "repeater out at {loc}, handheld only, range doesn't reach the far end"],
                "The repeater at {loc} has failed, leaving only handhelds whose range barely covers the site.",
                cause="repeater failure", asset="repeater",
                resources=["repeater repair", "relay arrangement"], hint="{loc}",
            ),
            L(
                "CRITICAL", "UNKNOWN",
                ["repeater's gone at {loc} and {team} went past the handheld range {hours} hours ago",
                 "no repeater at {loc} and {team} has been out of handheld range for {hours} hours"],
                "The repeater at {loc} has failed while {team} has been beyond handheld range for {hours} hours.",
                cause="repeater failure with a team beyond range", asset="repeater",
                entities=["1 team beyond communications range"],
                resources=["repeater repair", "search team"], hint="{loc}",
            ),
        ],
    ),
    F(
        "comms_power_ladder",
        "COMMUNICATIONS",
        [
            L(
                "LOW", "OPEN",
                ["radios at {loc} are on charge, all good for the shift",
                 "{loc} radio batteries charged up, fine for today"],
                "Radios at {loc} are charged and sufficient for the shift.",
                cause="routine charging", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["radio batteries at {loc} are getting low and the charger's not working",
                 "{loc} handheld batteries running down, charger broken"],
                "Radio batteries at {loc} are running low with a non-functioning charger.",
                cause="charger failure", asset="radio charger",
                resources=["replacement charger", "spare batteries"], hint="{loc}",
            ),
            L(
                "HIGH", "UNKNOWN",
                ["down to one working radio at {loc} on its last bar, after that we have nothing",
                 "one radio left at {loc} with minimal charge, no comms after it dies"],
                "Only one radio remains at {loc} with minimal charge, after which communications will be lost.",
                cause="imminent loss of radio capability",
                resources=["power source", "spare batteries"], hint="{loc}",
            ),
        ],
    ),
    F(
        "comms_checkin_ladder",
        "COMMUNICATIONS",
        [
            L(
                "LOW", "OPEN",
                ["{team} missed their check in at {loc}, came through a few minutes late, all fine",
                 "late check in from {team} at {loc}, only by a few minutes, no issue"],
                "{team} checked in a few minutes late at {loc} with no issue.",
                cause="late check-in", resources=[], hint="{loc}",
            ),
            L(
                "HIGH", "UNKNOWN",
                ["{team} has missed two check ins from {loc} now, nothing since",
                 "two missed check ins from {team} at {loc}, no contact since the last one"],
                "{team} has missed two consecutive check-ins from {loc} with no contact since.",
                cause="missed check-ins", entities=["1 team out of contact"],
                resources=["communications attempt", "standby search team"], hint="{loc}",
            ),
            L(
                "CRITICAL", "UNKNOWN",
                ["{team} is {hours} hours overdue from {loc} with no contact, well past the margin",
                 "no word from {team} out of {loc} for {hours} hours, far beyond the safety margin"],
                "{team} is {hours} hours overdue from {loc} with no contact, well beyond the safety margin.",
                cause="team overdue and uncontactable", entities=["1 team overdue"],
                resources=["search team"], hint="{loc}",
            ),
        ],
    ),
    F(
        "comms_cause_ambiguous",
        "COMMUNICATIONS",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["can't raise {team} from {loc}, could be their radio, could be the terrain, could be anything",
                 "{team} not answering out of {loc}, might be equipment, might be the valley, no way to tell"],
                "{team} cannot be raised from {loc}, with equipment failure and terrain both possible explanations.",
                cause="undetermined", entities=["1 team not responding"],
                resources=["alternative contact method"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
                note="Silence is ambiguous: a flat battery and a casualty look identical on the radio.",
            ),
            L(
                "LOW", "OPEN",
                ["{team} is fine, they'd moved into the dead ground below {loc}, back in contact now",
                 "{team} reappeared, they were in the shadow below {loc}, contact restored"],
                "{team} has re-established contact, having been in dead ground below {loc}.",
                cause="terrain shadowing, resolved", resources=[], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "comms_status_conflicting",
        "COMMUNICATIONS",
        [
            L(
                "HIGH", "UNKNOWN",
                ["one report says the {loc} network is back and another says it's still down, both from the last ten minutes",
                 "conflicting accounts of {loc} network status within the last ten minutes, up and down"],
                "Reports from the last ten minutes conflict on whether the network at {loc} has been restored.",
                cause="network status disputed", resources=["direct verification"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "OPEN",
                ["{loc} network is partly back, works on the high side and not in the valley, which explains the disagreement",
                 "partial restoration at {loc}, high ground has signal and low ground doesn't"],
                "The network at {loc} is partially restored, working on high ground but not in the valley.",
                cause="partial network restoration", resources=["full restoration"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "comms_restored_info",
        "COMMUNICATIONS",
        [
            L(
                "LOW", "OPEN",
                ["comms fully restored at {loc}, everything back to normal",
                 "network and radio both back at {loc}, no issues"],
                "Communications have been fully restored at {loc}.",
                cause="communications restored", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "LOW", "OPEN",
                ["swapped the {loc} antenna, signal's much better now than before the fault",
                 "new antenna at {loc} has improved the signal beyond what it was"],
                "An antenna replacement at {loc} has improved signal beyond its pre-fault level.",
                cause="antenna replacement", asset="antenna", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
    ),
    F(
        "comms_multi_message_loss",
        "COMMUNICATIONS",
        [
            L(
                "CRITICAL", "UNKNOWN",
                ["[1150] {team} signal weak from {loc}\n[1220] missed check in\n[1400] nothing for {hours} hours, they're overdue",
                 "0800 weak signal {team} at {loc}\n0900 check in missed\n1100 {hours} hours silent, overdue"],
                "Messages track {team} from a weak signal at {loc} to silence and being {hours} hours overdue.",
                cause="progressive loss of contact with a team",
                entities=["1 team overdue"], resources=["search team"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[1310] lost {team} from {loc}\n[1325] tried the alternate channel\n[1330] back in contact, they'd changed frequency",
                 "1030 {team} silent at {loc}\n1040 alternate channel tried\n1045 contact restored, wrong frequency"],
                "Contact with {team} at {loc} was lost briefly and restored on an alternate channel after a frequency error.",
                cause="frequency error, resolved", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

ROAD_BLOCKAGE_FAMILIES = [
    F(
        "road_obstruction_ladder",
        "ROAD_BLOCKAGE",
        [
            L(
                "LOW", "OPEN",
                ["bit of debris on the shoulder at {loc}, traffic's going past fine",
                 "some rubble on the verge at {loc}, road's clear"],
                "Debris on the shoulder at {loc} is not obstructing traffic.",
                cause="debris on the verge", resources=["clearance when convenient"], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["{obstruction} across one lane at {loc}, vehicles getting past single file",
                 "one lane blocked at {loc} by {obstruction}, traffic alternating"],
                "{obstruction} is blocking one lane at {loc}, with traffic passing single file.",
                cause="{obstruction}", resources=["clearance crew"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["{obstruction} has closed {loc} completely, nothing's getting through in either direction",
                 "{loc} fully blocked by {obstruction}, no way past either way"],
                "{obstruction} has completely closed {loc} to traffic in both directions.",
                cause="{obstruction}", resources=["heavy clearance equipment", "alternative route"], hint="{loc}",
            ),
        ],
        slots={"obstruction": ["a fallen tree", "a landslip", "rockfall", "an overturned trailer"]},
    ),
    F(
        "road_criticality_ladder",
        "ROAD_BLOCKAGE",
        [
            L(
                "LOW", "OPEN",
                ["{loc} road is blocked but there's a good alternative route two minutes longer",
                 "blockage at {loc}, alternative road adds two minutes, no real impact"],
                "The road at {loc} is blocked, with a good alternative route adding only minutes.",
                cause="road blockage with alternative available",
                resources=["clearance when convenient"], hint="{loc}",
                note="Same blockage, different consequence — consequence is what moves severity here.",
            ),
            L(
                "MEDIUM", "BLOCKED",
                ["{loc} is blocked and it's the only road in, the detour is {hours} hours round",
                 "no alternative to {loc} except a {hours} hour detour, and it's blocked"],
                "The sole road at {loc} is blocked, leaving only a {hours}-hour detour.",
                cause="blockage of the only route",
                resources=["clearance crew"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["{loc} is blocked, it's the only way out, and we have a casualty who needs to be moved now",
                 "sole route at {loc} blocked with a critical casualty waiting to be taken out"],
                "The only route out at {loc} is blocked while a casualty requires immediate transport.",
                cause="blockage of the only route during a medical emergency",
                entities=["1 casualty awaiting transport"],
                resources=["immediate clearance", "air transport if available"], hint="{loc}",
            ),
        ],
    ),
    F(
        "road_surface_ladder",
        "ROAD_BLOCKAGE",
        [
            L(
                "LOW", "OPEN",
                ["pothole opening up on the {loc} road, easy to drive round for now",
                 "hole in the surface at {loc}, avoidable, worth fixing sometime"],
                "A pothole on the road at {loc} is avoidable and warrants routine repair.",
                cause="road surface wear", resources=["road repair"], hint="{loc}",
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["the {loc} road edge has washed out about half a lane wide, light vehicles only",
                 "washout at the {loc} road edge taking half a lane, restricting to light vehicles"],
                "A washout has taken roughly half a lane of the road at {loc}, restricting it to light vehicles.",
                cause="road edge washout", resources=["road repair"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["the {loc} road surface has gone entirely across a {count} metre stretch, impassable to anything",
                 "{count} metres of the {loc} road has washed away, nothing can cross"],
                "A {count}-metre stretch of road at {loc} has washed away entirely and is impassable.",
                cause="road washout", resources=["road reconstruction", "alternative route"], hint="{loc}",
            ),
        ],
    ),
    F(
        "road_slope_ladder",
        "ROAD_BLOCKAGE",
        [
            L(
                "MEDIUM", "RESTRICTED",
                ["small stones coming down onto the {loc} road, nothing big yet but it's continuous",
                 "steady trickle of rock onto {loc}, small pieces, hasn't stopped"],
                "Small rocks are falling continuously onto the road at {loc}.",
                cause="ongoing minor rockfall", resources=["slope monitoring", "clearance"], hint="{loc}",
            ),
            L(
                "HIGH", "BLOCKED",
                ["slip has come down across {loc}, road's shut, and the slope above is still moving",
                 "landslip blocking {loc} with more movement visible above"],
                "A landslip has blocked the road at {loc} while the slope above continues moving.",
                cause="active landslip",
                resources=["slope assessment", "heavy clearance equipment"], hint="{loc}",
            ),
            L(
                "CRITICAL", "BLOCKED",
                ["slip across {loc} has caught a vehicle, {count} people were in it and we can't reach them",
                 "landslide at {loc} has buried a vehicle with {count} occupants, no access to them"],
                "A landslip at {loc} has caught a vehicle with {count} occupants who cannot be reached.",
                cause="landslip involving a vehicle",
                entities=["{count} people in the buried vehicle"],
                resources=["search and rescue", "heavy plant"], hint="{loc}",
            ),
        ],
    ),
    F(
        "road_secondhand_ambiguous",
        "ROAD_BLOCKAGE",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["a driver mentioned {loc} is blocked, didn't say by what or whether they'd seen it themselves",
                 "heard {loc} might be blocked, no detail on what or when, unverified"],
                "An unverified report suggests the road at {loc} is blocked, without detail on cause or timing.",
                cause="unconfirmed", resources=["verification"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
            L(
                "LOW", "OPEN",
                ["drove {loc} myself, it's clear, whatever was there has been moved",
                 "checked {loc} in person, road is open, no obstruction"],
                "Direct observation confirms the road at {loc} is clear and open.",
                cause="reported blockage no longer present", resources=[], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
    ),
    F(
        "road_passability_conflicting",
        "ROAD_BLOCKAGE",
        [
            L(
                "HIGH", "UNKNOWN",
                ["two drivers give opposite answers on {loc}, one got through and one turned back",
                 "conflicting reports on {loc}, one vehicle passed and another couldn't"],
                "Drivers give conflicting accounts of whether {loc} is passable.",
                cause="passability disputed", resources=["direct assessment"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["{loc} takes high clearance vehicles only, which is why one got through and one didn't",
                 "checked {loc}, passable with high clearance, not with ordinary cars"],
                "The road at {loc} is passable only to high-clearance vehicles, explaining the conflicting reports.",
                cause="partial passability by vehicle type",
                resources=["high-clearance transport"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
    ),
    F(
        "road_cleared_info",
        "ROAD_BLOCKAGE",
        [
            L(
                "LOW", "OPEN",
                ["{loc} is cleared and open again, normal traffic running",
                 "road reopened at {loc}, everything moving normally"],
                "The road at {loc} has been cleared and reopened to normal traffic.",
                cause="blockage cleared", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "RESTRICTED",
                ["{loc} is open but only one lane, the rest is still being cleared",
                 "partial reopening at {loc}, single lane while clearance continues"],
                "The road at {loc} has partially reopened to a single lane while clearance continues.",
                cause="partial clearance", resources=["continued clearance"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
    ),
    F(
        "road_multi_message_slip",
        "ROAD_BLOCKAGE",
        [
            L(
                "CRITICAL", "BLOCKED",
                ["[1440] stones on the {loc} road\n[1505] proper slip now, road shut\n[1530] second slip caught a vehicle, {count} inside",
                 "0650 rockfall {loc}\n0720 slip across the road\n0745 further slip onto a vehicle, {count} occupants"],
                "Messages from {loc} track rockfall escalating into a landslip that closed the road and then caught a vehicle with {count} occupants.",
                cause="escalating landslip involving a vehicle",
                entities=["{count} people in the caught vehicle"],
                resources=["search and rescue", "heavy plant"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[0930] tree down across {loc}\n[1010] crew on site cutting\n[1045] cleared, road open",
                 "1340 obstruction {loc}\n1405 clearance started\n1440 road reopened"],
                "A tree blocking {loc} was cleared by a crew and the road reopened.",
                cause="fallen tree, cleared", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
    ),
]

RESOURCE_SHORTAGE_FAMILIES = [
    F(
        "resource_water_ladder",
        "RESOURCE_SHORTAGE",
        [
            L(
                "LOW", "OPEN",
                ["water stock at {loc} is down to three days, delivery already booked",
                 "three days of water left at {loc}, resupply is scheduled"],
                "Water stock at {loc} covers three days with a delivery already scheduled.",
                cause="routine stock depletion", resources=["scheduled water delivery"], hint="{loc}",
                note="RESOURCE_SHORTAGE at its low end — a shortage being managed is not an emergency.",
            ),
            L(
                "HIGH", "OPEN",
                ["water at {loc} is down to a day for {bigcount} people and nothing's confirmed for delivery",
                 "one day of water for {bigcount} at {loc}, no confirmed resupply"],
                "Water stock at {loc} covers one day for {bigcount} people with no confirmed resupply.",
                cause="water stock depletion without confirmed resupply",
                entities=["{bigcount} people dependent"],
                resources=["drinking water"], hint="{loc}",
            ),
            L(
                "CRITICAL", "OPEN",
                ["water's out at {loc}, {bigcount} people and nothing left, some already going without since this morning",
                 "no water remaining at {loc} for {bigcount} people, some have had none since morning"],
                "Water has run out at {loc} for {bigcount} people, some of whom have been without since morning.",
                cause="water supply exhausted", entities=["{bigcount} people without water"],
                resources=["emergency water delivery", "water tankering"], hint="{loc}",
            ),
        ],
    ),
    F(
        "resource_medical_ladder",
        "RESOURCE_SHORTAGE",
        [
            L(
                "LOW", "OPEN",
                ["running low on dressings at {loc}, still a couple of weeks worth",
                 "dressings getting low at {loc}, a fortnight left"],
                "Dressing stock at {loc} is running low with roughly two weeks remaining.",
                cause="routine stock depletion", resources=["dressings"], hint="{loc}",
            ),
            L(
                "MEDIUM", "OPEN",
                ["out of the usual painkillers at {loc}, we have alternatives but they're not ideal",
                 "no standard analgesia left at {loc}, substitutes available but poor"],
                "Standard analgesia has run out at {loc}, with suboptimal substitutes available.",
                cause="analgesia stock exhausted", resources=["painkillers"], hint="{loc}",
            ),
            L(
                "CRITICAL", "OPEN",
                ["no oxygen left at {loc} and {smallcount} patients need it right now",
                 "oxygen exhausted at {loc} with {smallcount} people currently dependent on it"],
                "Oxygen has run out at {loc} with {smallcount} patients currently dependent on it.",
                cause="oxygen supply exhausted", entities=["{smallcount} patients requiring oxygen"],
                resources=["oxygen cylinders", "urgent medical resupply"], hint="{loc}",
            ),
        ],
    ),
    F(
        "resource_food_ladder",
        "RESOURCE_SHORTAGE",
        [
            L(
                "LOW", "OPEN",
                ["food stock at {loc} is fine for now, just noting we're into the reserve pallets",
                 "starting on the reserve food at {loc}, still comfortable"],
                "Food stock at {loc} has moved onto reserve supplies while remaining comfortable.",
                cause="routine stock rotation", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["food at {loc} will last about {hours} hours at current rates, need the delivery confirmed",
                 "roughly {hours} hours of food left at {loc}, delivery not yet confirmed"],
                "Food stock at {loc} will last approximately {hours} hours, with delivery unconfirmed.",
                cause="food stock depletion", resources=["food delivery"], hint="{loc}",
            ),
            L(
                "HIGH", "OPEN",
                ["today's distribution at {loc} emptied the store, {bigcount} people and nothing for tomorrow",
                 "food gone after today at {loc}, {bigcount} people with nothing scheduled"],
                "Food stock at {loc} was exhausted by today's distribution, leaving {bigcount} people with nothing scheduled.",
                cause="food stock exhausted", entities=["{bigcount} people dependent"],
                resources=["food rations"], hint="{loc}",
            ),
        ],
    ),
    F(
        "resource_shelter_ladder",
        "RESOURCE_SHORTAGE",
        [
            L(
                "LOW", "OPEN",
                ["plenty of blankets at {loc}, mild night forecast anyway",
                 "blanket stock fine at {loc}, and it's a mild night"],
                "Blanket stock at {loc} is sufficient, with mild conditions forecast.",
                cause="adequate stock", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["{count} blankets at {loc} for {bigcount} people, temperature dropping tonight",
                 "only {count} blankets for {bigcount} at {loc} with a cold night coming"],
                "Only {count} blankets are available at {loc} for {bigcount} people as temperatures drop.",
                cause="insufficient blanket stock",
                entities=["{bigcount} people", "{count} blankets available"],
                resources=["blankets"], hint="{loc}",
            ),
            L(
                "HIGH", "OPEN",
                ["no bedding at all at {loc} for {bigcount} people including {count} children, and it's freezing",
                 "nothing to sleep on at {loc} for {bigcount} people, {count} of them children, in freezing conditions"],
                "No bedding is available at {loc} for {bigcount} people including {count} children in freezing conditions.",
                cause="bedding stock exhausted in cold conditions",
                entities=["{bigcount} people without bedding", "{count} children"],
                resources=["blankets", "heated shelter"], hint="{loc}",
            ),
        ],
    ),
    F(
        "resource_estimate_ambiguous",
        "RESOURCE_SHORTAGE",
        [
            L(
                "MEDIUM", "UNKNOWN",
                ["we're low on {stock} at {loc}, nobody's counted it properly so I can't say how low",
                 "{stock} running down at {loc}, no accurate count, can't give a figure"],
                "{stock} is running low at {loc}, with no accurate count available to quantify it.",
                cause="stock depletion of unquantified extent",
                resources=["stock count", "{stock}"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
                note="No quantity may be invented. 'Low' without a count is the whole of what is known.",
            ),
            L(
                "HIGH", "OPEN",
                ["counted the {stock} at {loc}, there's {hours} hours worth for {bigcount} people",
                 "{stock} counted at {loc}, {hours} hours of supply for {bigcount}"],
                "A count of {stock} at {loc} shows {hours} hours of supply for {bigcount} people.",
                cause="stock depletion, quantified", entities=["{bigcount} people dependent"],
                resources=["{stock}"], hint="{loc}",
                kind=KIND_AMBIGUOUS,
            ),
        ],
        slots={"stock": ["fuel", "drinking water", "food", "medical supplies"]},
    ),
    F(
        "resource_count_conflicting",
        "RESOURCE_SHORTAGE",
        [
            L(
                "HIGH", "UNKNOWN",
                ["the {stock} figures for {loc} don't match, the store says {hours} hours and the log says days",
                 "two different {stock} counts at {loc}, {hours} hours in one and several days in the other"],
                "Stock figures for {stock} at {loc} conflict between {hours} hours and several days of supply.",
                cause="stock quantity disputed",
                resources=["physical stock count"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
            L(
                "MEDIUM", "OPEN",
                ["physically counted the {stock} at {loc}, it's {hours} hours, the log hadn't been updated",
                 "{stock} count done at {loc}, {hours} hours actual, the records were stale"],
                "A physical count of {stock} at {loc} confirms {hours} hours of supply; records were out of date.",
                cause="stock depletion, count confirmed", resources=["{stock}"], hint="{loc}",
                kind=KIND_CONFLICTING,
            ),
        ],
        slots={"stock": ["fuel", "water", "rations", "dressings"]},
    ),
    F(
        "resource_resupply_info",
        "RESOURCE_SHORTAGE",
        [
            L(
                "LOW", "OPEN",
                ["resupply arrived at {loc}, stores are full again",
                 "delivery in at {loc}, everything restocked"],
                "A resupply delivery has arrived at {loc} and stores are replenished.",
                cause="resupply received", resources=[], hint="{loc}",
                kind=KIND_INFO,
            ),
            L(
                "MEDIUM", "OPEN",
                ["delivery came to {loc} but half of it was the wrong items, still short on {stock}",
                 "{loc} resupply arrived incomplete, wrong items, {stock} still short"],
                "A resupply at {loc} arrived with incorrect items, leaving {stock} still short.",
                cause="incorrect resupply delivery", resources=["{stock}"], hint="{loc}",
                kind=KIND_INFO,
            ),
        ],
        slots={"stock": ["fuel", "water", "rations", "dressings"]},
    ),
    F(
        "resource_multi_message_depletion",
        "RESOURCE_SHORTAGE",
        [
            L(
                "CRITICAL", "OPEN",
                ["[0800] {stock} getting low at {loc}\n[1400] under a day left\n[1900] gone, {bigcount} people affected",
                 "0700 {stock} running down {loc}\n1300 less than a day\n1800 exhausted, {bigcount} affected"],
                "Messages track {stock} at {loc} depleting through the day until exhausted, affecting {bigcount} people.",
                cause="stock exhaustion", entities=["{bigcount} people affected"],
                resources=["emergency resupply of {stock}"], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
            L(
                "LOW", "OPEN",
                ["[0930] {stock} low at {loc}\n[1200] delivery confirmed\n[1530] delivered, back to normal levels",
                 "1000 {stock} short {loc}\n1230 resupply confirmed\n1600 arrived, stocks normal"],
                "{stock} ran low at {loc} before a confirmed delivery arrived and restored normal levels.",
                cause="stock depletion resolved by resupply", resources=[], hint="{loc}",
                kind=KIND_MULTI_MESSAGE,
            ),
        ],
        slots={"stock": ["water", "fuel", "rations", "medical supplies"]},
    ),
]

INFRA_FAMILIES = (
    INFRASTRUCTURE_FAMILIES
    + POWER_FAMILIES
    + COMMUNICATIONS_FAMILIES
    + ROAD_BLOCKAGE_FAMILIES
    + RESOURCE_SHORTAGE_FAMILIES
)
